# Use travis in https://github.com/Opetushallitus/eperusteet-ylops to deploy
# This is only for running tests

language: node_js

node_js:
  - "10.14.2"

before_script:
  - npm install

script:
  - npm run ci

cache:
  directories:
    - $HOME/.npm
