sudo: false
language: node_js

env:
  - YLOPS_SERVICE_DIR=$PWD/eperusteet-ylops/eperusteet-ylops-service

node_js:
  - "10.15.0"

install:
  - npm ci

script:
  - git clone https://github.com/Opetushallitus/eperusteet-ylops
  - cd eperusteet-ylops && mvn dependency:resolve --quiet && cd ..
  - npm run gen:api
  - npm run ci:start

cache:
  npm: true
  directories:
    - $HOME/.npm
    - $HOME/.m2
    - $HOME/.cache
