sudo: false

language: java

jdk:
  - openjdk8

env:
  global:
    - YLOPS_SERVICE_DIR=$PWD/eperusteet-ylops/eperusteet-ylops-service
    - EPERUSTEET_SERVICE_DIR=$PWD/eperusteet/eperusteet/eperusteet-service
    - secure: BMurlh1XguXVumsVbtnWrhRTewpX3hDIlg3BzCT+vDjBkNIsgMs9vWOTQrt4+1rrxdOPlCEsRiRUO+AxRiVbgK91BJPNlsWzuxQGSeQ0tqRr9BiqZoDBtrnj01c0fcu0Miea/0Pbz0P1BaGzrU6w12FX5M8ooudda5NBrvxpLRuyM5Z3TSVbbqxvhBRppdAa2QPKp3h7KQp6BDjdXSAUZ0QKzManM26rH0doj4AsGpfzriaAdX3u7vwdQWwTWX4Ah/6/wIxY3z+c1Hq0AIl8aON0+i98K48ubOy8K+X32EsWPqeS+Th+BSMDEoLq9ONlTsjrzdzF5movngnQ3FdFfYzoXe5JOTHtR8itNF0C+3nBqCM/47evndMzpw3whb3qeF3SO3EMD8R9VDobCvVAtNDD4TWud8f1YzEbOYp/OAhGkCXpz3jFOoWxwGGhuCLTPCsXXzc+pt0OieBbbtRTeYSTUPS6CNOoERBA6oXPTT5DkurUxsQd1svpXRGAjiNe2S2HVQpyI+Gs0XSWdY8FP68lbYqhgImMuvOahYN6+B6jyRO6+Mx7GUsiSt/oF7xwGHS434MAqVBVSoul3Fg1TgKrnxFn4D7+4wm53KFoLXgHR4ASS0+mp8xYv3TL/YnAN/jrFY6AsqET6I/0/gANLl+J3gZkICLw1PczomzpEgw=

install:
  - nvm install 10.16.3
  - git clone --depth=1 https://github.com/Opetushallitus/eperusteet-ylops
  - git clone --depth=1 https://github.com/Opetushallitus/eperusteet
  - git submodule update --recursive --init

  - echo 'Generate API...' && echo -en 'travis_fold:start:script.1\\r'
  - cd eperusteet/eperusteet && mvn dependency:resolve --batch-mode && cd ../..
  - cd eperusteet-ylops && mvn dependency:resolve --batch-mode && cd ..
  - echo -en 'travis_fold:end:script.1\\r'

  - yarn install --silent
  - yarn gen:api

  - cd eperusteet-frontend-utils/vue
  - yarn install --silent
  - yarn gen:api # FIXME
  - rm -rf node_modules
  - cd ../..

before_script:
  - echo $JAVA_HOME
  - java -version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nvm install 10.16.3
  - yarn lint
  - yarn build
  - yarn test:unit

after_script:
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
  - ./cc-test-reporter upload-coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.m2
    - $HOME/.cache

deploy:
  provider: releases
  api_key:
    secure: "emhRVszFIxtDo7dZJyVirQg4zAriqfjYqtK+/WUkCTZbsQ7c/EBq04XBCIlDtVs5V8nkhZXsBr6RAOjK89kLBAIG4wVr1LYGEHbz4iLuvUWTTUCTvZfIiji9M+L6KRpWzjRpFopGHxn7CPqC9BAk2hj9XUVSPxYaj0Q7BQf1/z0ciKkmhDUQz2WWdSwiVOlWG2g3EQBbwVWbUMP6LC3vCqB2CrmuWWrd7WM7k6ndfYjt8haKNuUA66qUxfiHvTbZx7tn8xn96MpUffp1yqfiqjU6EpcdqOMI9RPIwiRtZ6LWU9RMmdcQ/v7q868jlopmLyPk2Ht/HyGxyYFJLfBIQfCGc9uDbRw/oLgfIBLYXV4zKsQ/rOUSOl2P3C1T0biuKTkXo45RKw1CiEjv7nDFZY+WwadZWlsAScWTW/kSUStmltHbOs/F0j3IX1lgGoeTY7Wt6/D0NWxxqBggjjBz9zZYWEMHTH0buzKoNpNigROS9s/OXILsHMX/NwIUq4iUnj+KbKJga6zR0a5+6ztvoCtwnP1iQSOmXd9sWLj2ZhKL+ifFsrAUdv38Nltwhypd2povSKmOfLweDoq+1PIEhl89Awwfr5o+205lzvI8wXmxKu9+30CiREtWLQVnSs6Ps2JfWiY0tIEtQQR5xZS5ONMGU/dnDwMe43vGAdDQl2g="
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
