sudo: false
language: node_js

env:
  - YLOPS_SERVICE_DIR=$PWD/eperusteet-ylops/eperusteet-ylops-service

node_js:
  - 10.15.0

install:
  - git clone --branch uusi_lukio https://github.com/Opetushallitus/eperusteet-ylops
  - cd eperusteet-ylops && mvn dependency:resolve --quiet && cd ..
  - npm ci

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run gen:api
  - rm -rf eperusteet-ylops
  - npm run lint
  - npm run build
  - npm run test

after_script:
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
  - ./cc-test-reporter upload-coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  npm: true
  directories:
    - $HOME/.npm
    - $HOME/.m2
    - $HOME/.cache

addons:
  code_climate:
    repo_token:
      secure: "emhRVszFIxtDo7dZJyVirQg4zAriqfjYqtK+/WUkCTZbsQ7c/EBq04XBCIlDtVs5V8nkhZXsBr6RAOjK89kLBAIG4wVr1LYGEHbz4iLuvUWTTUCTvZfIiji9M+L6KRpWzjRpFopGHxn7CPqC9BAk2hj9XUVSPxYaj0Q7BQf1/z0ciKkmhDUQz2WWdSwiVOlWG2g3EQBbwVWbUMP6LC3vCqB2CrmuWWrd7WM7k6ndfYjt8haKNuUA66qUxfiHvTbZx7tn8xn96MpUffp1yqfiqjU6EpcdqOMI9RPIwiRtZ6LWU9RMmdcQ/v7q868jlopmLyPk2Ht/HyGxyYFJLfBIQfCGc9uDbRw/oLgfIBLYXV4zKsQ/rOUSOl2P3C1T0biuKTkXo45RKw1CiEjv7nDFZY+WwadZWlsAScWTW/kSUStmltHbOs/F0j3IX1lgGoeTY7Wt6/D0NWxxqBggjjBz9zZYWEMHTH0buzKoNpNigROS9s/OXILsHMX/NwIUq4iUnj+KbKJga6zR0a5+6ztvoCtwnP1iQSOmXd9sWLj2ZhKL+ifFsrAUdv38Nltwhypd2povSKmOfLweDoq+1PIEhl89Awwfr5o+205lzvI8wXmxKu9+30CiREtWLQVnSs6Ps2JfWiY0tIEtQQR5xZS5ONMGU/dnDwMe43vGAdDQl2g="
